### ISSUE TITLE
MSR-2_BLE.yaml incorrect bluetooth proxy yaml

### ISSUE THREAD

**Issue by bharvey88** [ApolloAutomation/MSR-2#22]
https://github.com/ApolloAutomation/MSR-2/blob/4b4ae348e6612bac65eef3bd398469323dc0dbc4/Integrations/ESPHome/MSR-2_BLE.yaml#L41-L42

please replace lines 41-42 with these for proper BLE proxy code:

```yaml
bluetooth_proxy:
  active: true
esp32_ble_tracker:
  scan_parameters:
    active: false
#we are required to use this old esp-idf framework that uses less space
esp32:
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
    ```
    
I also added the esp-idf downgrade as we will be using that going forward due to esp-idf ballooning in size and not being friendly with 4MB flash.
