### ISSUE TITLE
Base MSR-2 Configuration Invalid For ESPHome Device Builder Version 2025.2.0

### ISSUE THREAD

**Issue by compmodder26** [ApolloAutomation/MSR-2#23]
I just installed the latest version of ESPHome Device Builder (2025.2.0).  I attempted to edit the friendly name of one of my MSR-2 sensors.  When I attempted to install the updated configuration this error was thrown:

```
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/apollo-msr-2-aa1bc0.yaml...
Failed config

light.esp32_rmt_led_strip: [source /data/packages/9a51d7a7/Integrations/ESPHome/MSR-2.yaml:497]
  platform: esp32_rmt_led_strip
  id: rgb_light
  name: RGB Light
  pin: GPIO3
  
  This feature is not available for the IDF framework version 5.
  rmt_channel: 0
  default_transition_length: 0s
  chipset: WS2812
  num_leds: 3
  rgb_order: grb
  effects: 
    - pulse: 
        name: Slow Pulse
```

This error is coming from the base configuration as this is all I have in place for the configuration of the device:

```
substitutions:
  name: apollo-msr-2-aa1bc0
  friendly_name: Office Presence Sensor
packages:
  ApolloAutomation.MSR-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ***************************


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: scd4x
    id: !extend scd40 
    temperature:
      name: "SCD40 Temperature"
    humidity:
      name: "SCD40 Humidity"
```

Looking at the [documentation](https://esphome.io/components/light/esp32_rmt_led_strip.html#arduino-configuration-variables), it appears that `rmt_channel` is an Arduino configuration variable and may not be compatible with esp-idf.
